# Required
version: 2

sphinx:
  configuration: docsrc/conf.py

python:
  install:
    - requirements: docs/requirements.txt

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
