AUTH_URL = "{api_endpoint}/auth/v1/login"
ACCOUNT_URL = "/iam/v2/account"
GET_ENGINE_BY_NAME_URL = "/core/v1/account/engines:getIdByName"
ACCOUNT_ENGINE_URL = "/core/v1/accounts/{account_id}/engines/{engine_id}"
ACCOUNT_ENGINE_START_URL = ACCOUNT_ENGINE_URL + ":start"
ACCOUNT_ENGINE_STOP_URL = ACCOUNT_ENGINE_URL + ":stop"
ACCOUNT_DATABASE_URL = "/core/v1/accounts/{account_id}/databases/{database_id}"
