name: 'Build Documentation'
description: 'Build the Sphinx documentation'

inputs:
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      shell: bash
      run: |
        pip install -U pip
        pip install -e .[docs]

    - name: Build Sphinx documentation
      shell: bash
      run: |
        python -m sphinx -T -b html -d _build/doctrees -D language=en docsrc docs_compiled
        ls docs_compiled

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ inputs.github-token }}
        publish_dir: ./docs_compiled
        destination_dir: docs
