name: Build documenation

on:
  workflow_dispatch:
    inputs:
      custom-path:
        description: 'Custom path to deploy documentation to'
        required: false
        default: ''
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: 3.x

    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.cfg') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      shell: bash
      run: |
        pip install -U pip
        pip install -e .[docs]

    - name: Build Sphinx documentation
      shell: bash
      run: |
        python -m sphinx -T -b html -d _build/doctrees -D language=en docsrc docs_compiled

    - name: Resolve url path
      id: resolve_url_path
      shell: bash
      env:
        CUSTOM_PATH: ${{ github.event.inputs.custom-path }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        GITHUB_RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
      run: |
        if [[ -n "${CUSTOM_PATH}" ]]; then
            echo "path=${CUSTOM_PATH}" >> $GITHUB_OUTPUT
        # 0.x releases deploy to 0.x path, all other releases deploy to latest path
        elif [[ "${{ github.event_name }}" == "release" && "${GITHUB_RELEASE_TAG_NAME}" == 0.* ]]; then
            echo "path=0.x" >> $GITHUB_OUTPUT
        # for manual builds deploy to the branch name path
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "path=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
        else
            echo "path=latest" >> $GITHUB_OUTPUT
        fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs_compiled
        destination_dir: sdk_documenation/${{ steps.resolve_url_path.outputs.path }}

    - name: Add URL to the Job Summary
      shell: bash
      run: |
        url="https://old.docs.firebolt.io/firebolt-python-sdk/sdk_documenation/${{ steps.resolve_url_path.outputs.path }}"
        echo "[Documentation]($url)" >> $GITHUB_STEP_SUMMARY
