name: Integration tests
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FIREBOLT_STG_USERNAME:
        required: true
      FIREBOLT_STG_PASSWORD:
        required: true
      SERVICE_ID_STG:
        required: true
      SERVICE_SECRET_STG:
        required: true
      # V2 secrets
      FIREBOLT_CLIENT_ID_STG_NEW_IDN:
        required: true
      FIREBOLT_CLIENT_SECRET_STG_NEW_IDN:
        required: true
jobs:
  integration-test-v1:
    uses: ./.github/workflows/integration-tests-v1.yml
    secrets: inherit
  integration-test-v2:
    uses: ./.github/workflows/integration-tests-v2.yml
    secrets: inherit
    with:
      is_account_v2: false
  integration-test-account-v2:
    uses: ./.github/workflows/integration-tests-v2.yml
    secrets: inherit
    with:
      is_account_v2: true
  report-test-results:
    needs: [integration-test-v1, integration-test-v2, integration-test-account-v2]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Decorate commit
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Integration tests'
          description: "${{ contains(needs.*.result, 'failure') && 'Failed' || 'Successful' }}"
          state: "${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}"
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
