name: Integration tests
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FIREBOLT_CLIENT_ID_STG_NEW_IDN:
        required: true
      FIREBOLT_CLIENT_SECRET_STG_NEW_IDN:
        required: true
      ECOSYSTEM_FIREBOLT_SA_NO_USER_CLIENT_ID_STG:
        required: true
      ECOSYSTEM_FIREBOLT_SA_NO_USER_CLIENT_SECRET_STG:
        required: true

permissions:
  contents: read

jobs:
  integration-test-v2:
    uses: ./.github/workflows/integration-tests-v2.yml
    secrets:
      FIREBOLT_CLIENT_ID_STG_NEW_IDN: ${{ secrets.FIREBOLT_CLIENT_ID_STG_NEW_IDN }}
      FIREBOLT_CLIENT_SECRET_STG_NEW_IDN: ${{ secrets.FIREBOLT_CLIENT_SECRET_STG_NEW_IDN }}
      ECOSYSTEM_FIREBOLT_SA_NO_USER_CLIENT_ID_STG: ${{ secrets.ECOSYSTEM_FIREBOLT_SA_NO_USER_CLIENT_ID_STG }}
      ECOSYSTEM_FIREBOLT_SA_NO_USER_CLIENT_SECRET_STG: ${{ secrets.ECOSYSTEM_FIREBOLT_SA_NO_USER_CLIENT_SECRET_STG }}
  integration-test-core:
    uses: ./.github/workflows/integration-tests-core.yml
  report-test-results:
    permissions:
      statuses: write
    needs: [integration-test-v2, integration-test-core]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Decorate commit
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          NEEDS_RESULTS: ${{ toJSON(needs) }}
        with:
          script: |
            const failed = Object.values(JSON.parse(process.env.NEEDS_RESULTS))
              .some(job => job.result === 'failure');
            await github.rest.repos.createCommitStatus({
              ...context.repo,
              sha: context.payload.pull_request?.head.sha || context.sha,
              context: 'Integration tests',
              description: failed ? 'Failed' : 'Successful',
              state: failed ? 'failure' : 'success',
              target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
            });
