name: Integration tests FB 2.0
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FIREBOLT_CLIENT_ID_STG_NEW_IDN:
        required: true
      FIREBOLT_CLIENT_SECRET_STG_NEW_IDN:
        required: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Build Documentation
        uses: ./github/actions/build-documentation
