name: Integration tests
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the tests against'
        type: choice
        required: true
        default: 'dev'
        options:
          - dev
          - staging
  workflow_call:
    inputs:
      environment:
        default: 'staging'
        required: false
        type: string
      branch:
        required: false
        type: string
        description: 'Branch to run on'
    secrets:
      FIREBOLT_USERNAME:
        required: true
      FIREBOLT_PASSWORD:
        required: true
      FIREBOLT_STG_USERNAME:
        required: true
      FIREBOLT_STG_PASSWORD:
        required: true
      SERVICE_ID:
        required: true
      SERVICE_SECRET:
        required: true
      SERVICE_ID_STG:
        required: true
      SERVICE_SECRET_STG:
        required: true
      # V2 secrets
      FIREBOLT_CLIENT_ID_STG_NEW_IDN:
        required: true
      FIREBOLT_CLIENT_SECRET_STG_NEW_IDN:
        required: true
      FIREBOLT_CLIENT_ID_NEW_IDN:
        required: true
      FIREBOLT_CLIENT_SECRET_NEW_IDN:
        required: true
jobs:
  integration-test-v1:
    uses: ./.github/workflows/integration-tests-v1.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      branch: ${{ github.event.inputs.branch }}
    secrets:
      FIREBOLT_USERNAME: ${{ secrets.FIREBOLT_USERNAME }}
      FIREBOLT_PASSWORD: ${{ secrets.FIREBOLT_PASSWORD }}
      FIREBOLT_STG_USERNAME: ${{ secrets.FIREBOLT_STG_USERNAME }}
      FIREBOLT_STG_PASSWORD: ${{ secrets.FIREBOLT_STG_PASSWORD }}
      SERVICE_ID: ${{ secrets.SERVICE_ID }}
      SERVICE_SECRET: ${{ secrets.SERVICE_SECRET }}
      SERVICE_ID_STG: ${{ secrets.SERVICE_ID_STG }}
      SERVICE_SECRET_STG: ${{ secrets.SERVICE_SECRET_STG }}
  integration-test-v2:
    uses: ./.github/workflows/integration-tests-v2.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      branch: ${{ github.event.inputs.branch }}
    secrets:
      FIREBOLT_CLIENT_ID_STG_NEW_IDN: ${{ secrets.FIREBOLT_CLIENT_ID_STG_NEW_IDN }}
      FIREBOLT_CLIENT_SECRET_STG_NEW_IDN: ${{ secrets.FIREBOLT_CLIENT_SECRET_STG_NEW_IDN }}
      FIREBOLT_CLIENT_ID_NEW_IDN: ${{ secrets.FIREBOLT_CLIENT_ID_NEW_IDN }}
      FIREBOLT_CLIENT_SECRET_NEW_IDN: ${{ secrets.FIREBOLT_CLIENT_SECRET_NEW_IDN }}
