name: Integration tests FB 2.0
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FIREBOLT_CLIENT_ID_STG_NEW_IDN:
        required: true
      FIREBOLT_CLIENT_SECRET_STG_NEW_IDN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.3
  
      - name: Print Public IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}
