name: Integration tests for fork
on:
  pull_request_target:
    types: [opened, synchronize]
permissions:
  contents: read
  pull-requests: read
jobs:
  verify-no-changes-in-gh-actions:
    name: "Check fork does not change protected paths"
    if: github.event.pull_request.head.repo.fork == true
    runs-on: ubuntu-latest
    steps:
      - name: Check for changes in .github/workflows
        run: |
         git diff --exit-code .github/workflows

  setup-fork:
    name: "Setup fork context for integration tests"
    runs-on: ubuntu-latest
    needs: verify-no-changes-in-gh-actions
    outputs:
      database-name: ${{ steps.setup-fork-action.outputs.database_name }}
      engine-name: ${{ steps.setup-fork-action.outputs.engine_name }}
      stopped-engine-name: ${{ steps.setup-fork-action.outputs.stopped_engine_name }}
      sa-id: ${{ steps.setup-fork-action.outputs.sa_id }}
      sa-secret: ${{ steps.setup-fork-action.outputs.sa_secret }}
    steps:
      - name: Call local setup-fork-action action
        id: setup-fork-action
        uses: ./.github/actions/setup-fork-action
        with:
          firebolt-client-id: ${{ secrets.FIREBOLT_CLIENT_ID }}
          firebolt-client-secret: ${{ secrets.FIREBOLT_CLIENT_SECRET }}
          account: ${{ vars.FIREBOLT_ACCOUNT_V2 }}
          api-endpoint: "api.staging.firebolt.io"

  integration-test-fork:
    name: "Run integration tests"
    needs: [verify-no-changes-in-gh-actions, setup-fork]
    environment: restricted-fork-runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Run integration tests
        env:
          SERVICE_ID: ${{ steps.setup-fork.outputs.sa-id }}
          SERVICE_SECRET: ${{ steps.setup-fork.outputs.sa-secret }}
          DATABASE_NAME: ${{ steps.setup-fork.outputs.database-name }}
          ENGINE_NAME: ${{ steps.setup-fork.outputs.engine-name }}
          STOPPED_ENGINE_NAME: ${{ steps.setup-fork.outputs.stopped-engine-name }}
          API_ENDPOINT: "api.staging.firebolt.io"
          ACCOUNT_NAME_V1: ""
          ACCOUNT_NAME_V2: ${{ vars.FIREBOLT_ACCOUNT_V2 }}
        run: |
          pytest -n 6 --dist loadgroup --timeout_method "signal" -o log_cli=true -o log_cli_level=WARNING tests/integration -k "not V1"

