name: Integration tests
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FIREBOLT_CLIENT_ID_STG_NEW_IDN:
        required: true
      FIREBOLT_CLIENT_SECRET_STG_NEW_IDN:
        required: true
jobs:
  integration-test-v2:
    uses: ./.github/workflows/integration-tests-v2.yml
    secrets:
      FIREBOLT_CLIENT_ID_STG_NEW_IDN: ${{ secrets.FIREBOLT_CLIENT_ID_STG_NEW_IDN }}
      FIREBOLT_CLIENT_SECRET_STG_NEW_IDN: ${{ secrets.FIREBOLT_CLIENT_SECRET_STG_NEW_IDN }}
  integration-test-core:
    uses: ./.github/workflows/integration-tests-core.yml
  report-test-results:
    needs: [integration-test-v2, integration-test-core]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Decorate commit
        uses: Sibz/github-status-action@650dd1a882a76dbbbc4576fb5974b8d22f29847f # v1.1.6
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Integration tests'
          description: "${{ contains(needs.*.result, 'failure') && 'Failed' || 'Successful' }}"
          state: "${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}"
          sha: ${{github.event.pull_request.head.sha || github.sha}}
          target_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
