name: Nightly workflow
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        description: 'Branch to run on'
jobs:
  code-check:
    uses: ./.github/workflows/code-check.yml
    with:
      branch: ${{ inputs.branch }}
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    with:
      branch: ${{ inputs.branch }}
    secrets:
      GIST_PAT: ${{ secrets.GIST_PAT }}
  security-scan:
    needs: [unit-tests]
    uses: ./.github/workflows/security-scan.yml
    with:
      branch: ${{ inputs.branch }}
    secrets:
      FOSSA_TOKEN: ${{ secrets.FOSSA_TOKEN }}
      SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # finish all jobs even if one fails
      max-parallel: 2
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
    
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[dev]"

      - name: Unit test with pytest
        run: |
          pytest tests/unit

      - name: Setup database and engine
        id: setup
        uses: firebolt-db/integration-testing-setup@master
        with:
          firebolt-username: ${{ secrets.FIREBOLT_STG_USERNAME }}
          firebolt-password: ${{ secrets.FIREBOLT_STG_PASSWORD }}
          api-endpoint: "api.staging.firebolt.io"
          region: "us-east-1"
          db_suffix: ${{ format('{0}_{1}', matrix.os, matrix.python-version) }}

      - name: Run integration tests
        env:
          USER_NAME: ${{ secrets.FIREBOLT_STG_USERNAME }}
          PASSWORD: ${{ secrets.FIREBOLT_STG_PASSWORD }}
          SERVICE_ID: ${{ secrets.SERVICE_ID_STG }}
          SERVICE_SECRET: ${{ secrets.SERVICE_SECRET_STG }}
          DATABASE_NAME: ${{ steps.setup.outputs.database_name }}
          ENGINE_NAME: ${{ steps.setup.outputs.engine_name }}
          ENGINE_URL: ${{ steps.setup.outputs.engine_url }}
          STOPPED_ENGINE_NAME: ${{ steps.setup.outputs.stopped_engine_name }}
          STOPPED_ENGINE_URL: ${{ steps.setup.outputs.stopped_engine_url }}
          ACCOUNT_NAME: "firebolt"
          API_ENDPOINT: "api.staging.firebolt.io"
        run: |
          pytest --timeout_method "thread" -o log_cli=true -o log_cli_level=INFO --junit-xml=report/junit.xml tests/integration

      - name: Slack Notify of failure
        if: failure()
        id: slack
        uses: firebolt-db/action-slack-nightly-notify@v1
        with:
          os: ${{ matrix.os }}
          programming-language: Python
          language-version: ${{ matrix.python-version }}
          notifications-channel: 'ecosystem-ci-notifications'
          slack-api-key: ${{ secrets.SLACK_BOT_TOKEN }}
