name: Nightly workflow
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        description: 'Branch to run on'
jobs:
  code-check:
    uses: ./.github/workflows/code-check.yml
    with:
      branch: ${{ inputs.branch }}
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    with:
      branch: ${{ inputs.branch }}
    secrets:
      GIST_PAT: ${{ secrets.GIST_PAT }}
  security-scan:
    needs: [unit-tests]
    uses: ./.github/workflows/security-scan.yml
    with:
      branch: ${{ inputs.branch }}
    secrets:
      FOSSA_TOKEN: ${{ secrets.FOSSA_TOKEN }}
      SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # finish all jobs even if one fails
      max-parallel: 2
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
    
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[dev]"

      - name: Unit test with pytest
        run: |
          pytest tests/unit

