name: Pull request title check

on:
  pull_request:
    branches: [ main ]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
    - name: Convetional Commits Pull Request Title
      uses: jef/conventional-commits-pr-action@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
