name: Firebolt Security Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Security Scan"
        uses: firebolt-db/action-security-scan@main
