name: Firebolt Security Scan

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Download coverage report"
        uses: actions/download-artifact@v2
        with:
          name: pytest-coverage-report

      - name: "Security Scan"
        uses: firebolt-db/action-security-scan@main
        with:
          github-key: ${{ inputs.github-key }}
          fossa-key: ${{ inputs.fossa-key }}
          sonar-key: ${{ inputs.sonar-key }}
