name: Firebolt Security Scan

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Fossa branch fix"
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git fetch
          git branch --track ${GITHUB_HEAD_REF##*/} origin/${GITHUB_HEAD_REF##*/}
          git checkout ${GITHUB_HEAD_REF##*/}

      - name: "Build"
        run: |
          python3 -m pip install build
          python3 -m build

      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@v1
        with:
          api-key: ${{secrets.fossaApiKey}}

  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=firebolt-db
            -Dsonar.projectKey=firebolt-db_firebolt-python-sdk
            -Dsonar.sources=src
