name: Firebolt Security Scan

on: push

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      # - name: "Download coverage report"
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: pytest-coverage-report

      - name: "Security Scan"
        uses: firebolt-db/action-security-scan@fossa-fix-2
        with:
          github-key: ${{ secrets.GITHUB_TOKEN }}
          fossa-key: ${{ secrets.FOSSA_TOKEN }}
          sonar-key: ${{ secrets.SONARCLOUD_TOKEN }}
          
