name: Firebolt Security Scan

on:
  workflow_call:
    secrets:
      FOSSA_TOKEN:      
        required: true
      SONARCLOUD_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v2

      - name: "Download coverage report"
        uses: actions/download-artifact@v2
        with:
          name: pytest-coverage-report

      - name: "Security Scan"
        uses: firebolt-db/action-security-scan@main
        with:
          fossa-key: ${{ secrets.FOSSA_TOKEN }}
          sonar-key: ${{ secrets.SONARCLOUD_TOKEN }}
          github-key: ${{ secrets.GITHUB_TOKEN }}
