name: TEST new version

on:
  pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:    
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 
